### ISSUE TITLE
Additional solution (C.5.11)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#32]
**C.5.11 Solution to: Heroes of the Silver Screen Part 3**

It may be appropriate to show one more solution:

`mcTiernan.films.map(_.yearOfRelease).min`

**Comment by davegurnell** [comment]
Hey man. I just wanted to drop you a note to say "thanks" for all the issue reports. We're not ignoring you -- I'll do a pass over the whole book soon and deal with as many as I can!

**Comment by kosgdk** [comment]
All of these issues are my "thanks" for the authors for great bookы and for possibility to download them for free. So I'll be reporting issues as I read this and other books (Advanced Scala, Essential Slick, Essential Play)

**Comment by davegurnell** [comment]
I'd avoided mentioning `min` here because you need to know about implicits to understand how it works. However, I've seen plenty of trainees use `min` in our training courses and I now agree with you that it deserves a mention.

In the commit linked above I've added a mention of `min` together with a foreshadowing of the type class pattern. I've also added some notes about various methods like `min` and `head` throwing exceptions with empty lists.
